name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: aletheia

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Strategy matrix to handle environment-specific variables based on branch
    strategy:
      matrix:
        environment: [qa, prod]
        include:
          - environment: qa
            branch: develop
            suffix: -qa
          - environment: prod
            branch: main
            suffix: ''
            
    # Filter job execution based on branch
    if: (github.ref == 'refs/heads/main' && matrix.environment == 'prod') || (github.ref == 'refs/heads/develop' && matrix.environment == 'qa')

    environment: ${{ matrix.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Container
      run: |-
        IMAGE_TAG="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app:${{ github.sha }}"
        
        docker build -t $IMAGE_TAG \
          --build-arg VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
          --build-arg VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }} \
          --build-arg VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }} \
          --build-arg VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }} \
          --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} \
          --build-arg VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }} .
          
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}${{ matrix.suffix }}
        region: ${{ env.REGION }}
        image: ${{ env.IMAGE_TAG }}
        env_vars: |-
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          ENV=${{ matrix.environment }}
